image: microsoft/dotnet:latest

stages:
  - build
  - test

variables:
  project: "TestOne"

before_script:
  - "dotnet restore"

build:
  stage: build
  variables:
    build_path: "$project/src/$project"
  script:
    - "cd $build_path"
    - "dotnet build"

